### PR TITLE
Add check for fwd ref types

### PR DESCRIPTION
**Pull request by cristianbote**
This will make `forwardRef`(s) work with `@frontity/react-easy-state` and `@frontity/with-preact`.

### CODE REVIEW

**Comment by luisherranz** [comment]
Hey Cris, as this library is React-agnostic, shouldn't we do this in `view`/`connect`?

Something like this:

```js
const render = useMemo(
  () => {
    reaction.current = observe(isForwardRef ? Comp.render : Comp,
    // ...
```

**Comment by cristianbote** [comment]
> Hey Cris, as this library is React-agnostic, shouldn't we do this in `view`/`connect`?
> 
> Something like this:
> 
> ```js
> const render = useMemo(
>   () => {
>     reaction.current = observe(isForwardRef ? Comp.render : Comp,
>     // ...
> ```

Oh, right! Let me check.

**Comment by luisherranz** [comment]
Any luck?

**Comment by cristianbote** [comment]
Yeah this is not supposed to be fix in here for sure ✌️  closing and moving this to RES.

**Pull request closed without merging**
